import type { Theme, ThemeColors, ThemeName } from "./types";

export const themes: Record<ThemeName, Theme> = {
  "github-dark": {
    name: "github-dark",
    label: "github-dark",
    colors: {
      bg: "#0d1117",
      bgElevated: "#161b22",
      fg: "#c9d1d9",
      fgMuted: "#8b949e",
      fgFaint: "#484f58",
      accent: "#58a6ff",
      green: "#3fb950",
      red: "#f85149",
      yellow: "#d29922",
      blue: "#58a6ff",
      border: "#30363d",
      selection: "rgba(56, 139, 253, 0.18)",
    },
  },
  "github-light": {
    name: "github-light",
    label: "github-light",
    colors: {
      bg: "#ffffff",
      bgElevated: "#f6f8fa",
      fg: "#24292f",
      fgMuted: "#57606a",
      fgFaint: "#8c959f",
      accent: "#0969da",
      green: "#1a7f37",
      red: "#cf222e",
      yellow: "#9a6700",
      blue: "#0969da",
      border: "#d0d7de",
      selection: "rgba(9, 105, 218, 0.12)",
    },
  },
  "vercel-dark": {
    name: "vercel-dark",
    label: "vercel-dark",
    colors: {
      bg: "#000000",
      bgElevated: "#111111",
      fg: "#ffffff",
      fgMuted: "#a1a1aa",
      fgFaint: "#3f3f46",
      accent: "#ffffff",
      green: "#10b981",
      red: "#ef4444",
      yellow: "#f59e0b",
      blue: "#3b82f6",
      border: "#27272a",
      selection: "rgba(255, 255, 255, 0.15)",
    },
  },
  "vercel-light": {
    name: "vercel-light",
    label: "vercel-light",
    colors: {
      bg: "#ffffff",
      bgElevated: "#fafafa",
      fg: "#000000",
      fgMuted: "#71717a",
      fgFaint: "#e4e4e7",
      accent: "#000000",
      green: "#10b981",
      red: "#ef4444",
      yellow: "#f59e0b",
      blue: "#3b82f6",
      border: "#e4e4e7",
      selection: "rgba(0, 0, 0, 0.08)",
    },
  },
  "claude-dark": {
    name: "claude-dark",
    label: "claude-dark",
    colors: {
      bg: "#1b1816",
      bgElevated: "#26211e",
      fg: "#f7f4eb",
      fgMuted: "#b4b0a9",
      fgFaint: "#6e6a64",
      accent: "#e05c38",
      green: "#52a875",
      red: "#e05c38",
      yellow: "#e2b13c",
      blue: "#60a5fa",
      border: "#3a3530",
      selection: "rgba(224, 92, 56, 0.18)",
    },
  },
  "claude-light": {
    name: "claude-light",
    label: "claude-light",
    colors: {
      bg: "#fbfaf7",
      bgElevated: "#f5f2eb",
      fg: "#191919",
      fgMuted: "#6e6a64",
      fgFaint: "#b4b0a9",
      accent: "#d97753",
      green: "#3b7a57",
      red: "#c84b31",
      yellow: "#b8860b",
      blue: "#2563eb",
      border: "#e9e5dc",
      selection: "rgba(217, 119, 83, 0.12)",
    },
  },
};

export const defaultTheme: ThemeName = "github-dark";

export const themeOrder: ThemeName[] = [
  "github-dark",
  "github-light",
  "vercel-dark",
  "vercel-light",
  "claude-dark",
  "claude-light",
];

/** Build the inline CSS-variable style object for a theme. */
export function themeVars(colors: ThemeColors): Record<string, string> {
  return {
    "--bg": colors.bg,
    "--bg-elevated": colors.bgElevated,
    "--fg": colors.fg,
    "--fg-muted": colors.fgMuted,
    "--fg-faint": colors.fgFaint,
    "--accent": colors.accent,
    "--green": colors.green,
    "--red": colors.red,
    "--yellow": colors.yellow,
    "--blue": colors.blue,
    "--border": colors.border,
    "--selection": colors.selection,
  };
}
